spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  flyway:
    baseline-on-migrate: true

